---
- name: Creates directory
  file:
    path: /home/ubuntu/backend/
    state: directory

- name: Copy backend files
  copy:
    src: dist.zip
    dest: /home/ubuntu/backend/

- name: 
  ansible.builtin.unarchive:
    src: /home/ubuntu/backend/dist.zip
    dest: /home/ubuntu/backend/
    remote_src: yes

- name: Executing node
  shell: |
    pm2 start npm -- run start