---
- name: Creates directory
  file:
    path: /home/ubuntu/backend/
    state: directory

- name: Copy backend files
  copy:
    src: "~/"
    dest: "/home/ubuntu/backend/"
    remote_src: no

- name: Executing node
  shell: |
    pm2 start npm -- run start